176364 setup stryker and codecoverage
UKHO/s-100-permit-service pull request #12
Opened 2024-09-11 09:50 UTC by nerellavinod

Created the stryker job & published the report to pipeline and set code coverage threshold to 90% in the pipeline.

2024-09-11 11:07 UTC, harshal11869 requested changes

2024-09-11 11:07 UTC, harshal11869 commented on azure-pipelines.yml
> +            displayName: "Code coverage fails if threshold exceeded"
```suggestion
            displayName: "Code coverage fails if threshold not meet"            
```

2024-09-11 11:47 UTC, harshal11869 approved these changes
LGTM.

2024-09-11 11:50 UTC, nerellavinod commented on azure-pipelines.yml
> +            displayName: "Code coverage fails if threshold exceeded"
resolved this suggestion.

2024-09-12 06:54 UTC, harshal11869 approved these changes

2024-09-13 07:00 UTC, amogh14893 approved these changes
LGTM

2024-09-13 08:33 UTC, jrippington approved these changes
Looks good, thanks!

2024-09-13 08:33 UTC, merged