176372 retry mechanism for endpoints
UKHO/s-100-permit-service pull request #24
Opened 2024-10-01 08:15 UTC by mayur1501364

Consist changes of [PBI 176372](https://dev.azure.com/ukhydro/S-100%20Permit%20Generator/_workitems/edit/176372)

- Added retry mechanism
- Added unit test cases

2024-10-01 13:29 UTC, shirinbt14926 reviewed
Minor comments please

2024-10-01 13:29 UTC, shirinbt14926 commented on tests/UKHO.S100PermitService.Common.UnitTests/Services/UserPermitServiceTests.cs
> +        public void WhenUserPermitServiceResponseTooManyRequest_ThenResponseShouldNotBeOk(HttpStatusCode statusCode, string content)
```suggestion
        public void WhenUserPermitServiceResponseTooManyRequests_ThenResponseShouldNotBeOk(HttpStatusCode statusCode, string content)
```

2024-10-01 13:50 UTC, mayur1501364 commented on src/UKHO.S100PermitService.Common/Handlers/WaitAndRetryPolicy.cs
> +                                 .LogInformation(eventId.ToEventId(), "Re-trying service request with uri {RequestUri} and delay {delay}ms and retry attempt {retry} with _X-Correlation-ID:{correlatio
Changed the log

2024-10-01 13:54 UTC, mayur1501364 commented on src/UKHO.S100PermitService.Common/Events/EventIds.cs
> +        RetryHttpClientPKSRequest = 840033
Changed event name

2024-10-01 13:54 UTC, mayur1501364 commented on tests/UKHO.S100PermitService.Common.UnitTests/Services/UserPermitServiceTests.cs
> +        public void WhenUserPermitServiceResponseTooManyRequest_ThenResponseShouldNotBeOk(HttpStatusCode statusCode, string content)
changed test case name

2024-10-03 06:35 UTC, shirinbt14926 approved these changes
LGTM. Thanks @mayur1501364  for making changes

2024-10-03 09:18 UTC, harshal11869 approved these changes
Looks Good,

2024-10-04 04:35 UTC, harshal11869 requested changes

2024-10-04 04:35 UTC, harshal11869 commented on src/UKHO.S100PermitService.Common/Handlers/WaitAndRetryPolicy.cs
> +                                 var correlationId = response.Result.RequestMessage!.Headers.FirstOrDefault(h => h.Key.ToLowerInvariant() == "x-correlation-id");
```suggestion
                                 var correlationId = response.Result.RequestMessage!.Headers.FirstOrDefault(h => h.Key.ToLowerInvariant() == PermitServiceConstants.XCorrelationIdHeaderKey.ToLowerInvariant());
```

2024-10-04 04:58 UTC, shailen14599 commented on src/UKHO.S100PermitService.Common/Handlers/WaitAndRetryPolicy.cs
> +                                 var correlationId = response.Result.RequestMessage!.Headers.FirstOrDefault(h => h.Key.ToLowerInvariant() == "x-correlation-id");
Resolved

2024-10-04 05:51 UTC, jrippington approved these changes
Looks good, thanks!

2024-10-04 05:52 UTC, harshal11869 approved these changes
LGTM.

2024-10-04 06:33 UTC, merged