172916 - build permit xml
UKHO/s-100-permit-service pull request #32
Opened 2024-10-15 08:16 UTC by mayur1501364

This PR consist of code changes for [PBI 172916](https://dev.azure.com/ukhydro/S-100%20Permit%20Generator/_workitems/edit/172916)

- Code changes added
- Unit Test cases added
- Xsd validation and file added

2024-10-15 10:24 UTC, harshal11869 requested changes

2024-10-15 10:24 UTC, harshal11869 commented on src/UKHO.S100PermitService.Common/Services/PermitService.cs
> +        private Dictionary<string, Permit> _permitDictionary = new Dictionary<string, Permit>();
```suggestion
        private Dictionary<string, Permit> _permitDictionary = new();
```

2024-10-15 10:24 UTC, harshal11869 commented on src/UKHO.S100PermitService.Common/Services/PermitService.cs
> +                    products = new Products();
```suggestion
                    var dataPermit = new ProductsProductDatasetPermit
                    {
                        EditionNumber = byte.Parse(cell.LatestEditionNumber),
                        EncryptedKey = "encryptedkey",
                        Filename = cell.CellCode,
                        Expiry = holding.ExpiryDate
                    };
                    
                    if(productsList.Any(x => x.Id == products.Id))
                    {
                        productsList.FirstOrDefault(x => x.Id == products.Id).DatasetPermit.Add(dataPermit);
                    }
                    else
                    {
                        products.DatasetPermit = new List<ProductsProductDatasetPermit> { dataPermit };
                        productsList.Add(products);
                    }
                    products = new Products();
```

2024-10-15 11:08 UTC, mayur1501364 commented on src/UKHO.S100PermitService.Common/Services/PermitService.cs
> +        private Dictionary<string, Permit> _permitDictionary = new Dictionary<string, Permit>();
Changed.

2024-10-15 11:10 UTC, mayur1501364 commented on src/UKHO.S100PermitService.Common/Services/PermitService.cs
> +                    products = new Products();
Fixed the formatting

2024-10-15 11:10 UTC, mayur1501364 commented on src/UKHO.S100PermitService.Common/IO/PermitReaderWriter.cs
> +            var xsdPath = Path.Combine(_schemaDirectory, "XmlSchema", "Permit_Schema.xsd");
Constants added

2024-10-16 07:03 UTC, shirinbt14926 approved these changes
LGTM

2024-10-16 08:57 UTC, Nadeem14456 commented
Changes from this PR will be merged into PR #33. Hence Closing this.

2024-10-16 08:57 UTC, closed without merging