171325 devops create cd pipeline
UKHO/s-100-permit-service pull request #6
Opened 2024-08-29 06:12 UTC by nerellavinod

- Created CD pipeline for Dev, vNextIAT, vNextE2E environments.
- Azure resources created ( Webapp, Appinsight, KeyValut & EventHub ) using Terraform scripts and deployed on Dev environment.

2024-08-30 09:26 UTC, amogh14893 reviewed
Are these output variables being used for current scope of work. Re review the output variables across modules , retain those if getting used under current PBI scope.

2024-09-02 13:59 UTC, amogh14893 requested changes

2024-09-02 13:59 UTC, amogh14893 commented on Deployment/terraform_conditional_run.ps1
Could you please rename 'mock' output variables with 'stub' . Additionally verify what all variables we need , apart from  api webapp , stub webapp and key vault URL there should not be any

2024-09-02 13:59 UTC, amogh14893 commented on azure-pipelines.yml
Please review the output variables in  **DevDeployApp** Job.  if not required those can be removed and handled at stage level if possible.

2024-09-03 06:18 UTC, nerellavinod commented on Deployment/Modules/Webapp/main.tf
Resolved the comment

2024-09-03 06:24 UTC, nerellavinod commented on Deployment/Modules/Webapp/main.tf
Resolved the comment.

2024-09-03 06:50 UTC, amogh14893 commented on Deployment/Modules/Webapp/outputs.tf
Please correct output variables with prefix 'mock'. We are not using mock anywhere

2024-09-03 06:50 UTC, amogh14893 commented on Deployment/main.tf
Please correct webapp name variables for mock to stub.

2024-09-03 08:22 UTC, jrippington requested changes
Few minor corrections needed, thanks!

2024-09-03 08:58 UTC, nerellavinod commented on Deployment/Modules/Webapp/main.tf
> +      dotnet_version = "v6.0"
resolved now.

2024-09-03 08:59 UTC, nerellavinod commented on Deployment/Modules/Webapp/main.tf
> +      dotnet_version = "v6.0"
resolved now.

2024-09-03 11:04 UTC, jrippington approved these changes
Looks good

2024-09-03 11:04 UTC, merged